
# @import ../../auth/http/verify-otp.http

@baseUrl = http://localhost:8080

### 2. Get All Users (با توکن)
# @ref login
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{login.accessToken}}
###

### 2. Get User By ID
# @ref login

GET {{baseUrl}}/users/my-profile
Content-Type: application/json
Authorization: Bearer {{login.accessToken}}
